name: CI
on: 
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Perform Tests
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Test Conversion — Default paramaters
        uses: ./ # Uses action in the root directory
        with:
          INPUT_FILE: '.github/workflows/testfile-in.ai'

      - name: Test Conversion — Optional GS + file paramaters
        uses: ./ # Uses action in the root directory
        with:
          INPUT_FILE: '.github/workflows/testfile-in.ai'
          OUTPUT_FILE: 'build/testfile-out.pdf'
          OPTIONAL_PARAMS: '-dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer'

      - name: Display Results
        run: |
          git show --summary
          
          echo "Input file:"
          du -h .github/workflows/testfile-in.ai

          echo "Default option file:"
          du -h build/output.pdf

          echo "Output file:"
          du -h build/testfile-out.pdf
